title: Tolulope Ladele # your name (or website title) here
logo: "/images/IMG_2631.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <p><strong>DATA ANALYST</strong>
  <br><br>
  <p><strong>About Me</strong>
  <br><br>
  Hello! I'm Tolulope Ladele, an aspiring data analyst with a strong foundation in data visualization, statistical analysis, and data-driven decision-making. With expertise in Azure, Power BI, Tableau, Python, and R, I am well-equipped to turn complex data into actionable insights.
  <p><strong>My technical skills include: </strong>
  Azure, Power BI & Tableau, Python & R, Machine learning
  <br><br>
  <a href="https://www.linkedin.com/in/tolulope-lad">View My LinkedIn Profile</a> 
  <br> <br>
  <a href="https://public.tableau.com/app/profile/tolulope.ladele/vizzes">View My Tableau Public</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
