title: Tolulope Ladele # your name (or website title) here
logo: "/images/IMG_2631.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <p><strong>DATA ANALYST</strong>
  <p><strong>About Me</strong>
  Hello! I'm Tolulope Ladele, I specialize in transforming complex data into actionable insights through data visualization and statistical analysis. 
 <p><strong>My technical skills include: </strong>
  Azure, Power BI & Tableau, Python & R, Machine learning
  <br><br>
  <a href="https://www.linkedin.com/in/tolulope-lad">View My LinkedIn Profile</a> 
  <br> <br>
  <a href="https://public.tableau.com/app/profile/tolulope.ladele/vizzes">View My Tableau Public</a> 
  

plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
